In [1]:
import pandas as pd
from functools import reduce

pd.set_option('display.max_rows', None)

dates = pd.read_csv('csv_from_scrape/baseball_dates_index.csv')

In [2]:
davis_2017 = pd.read_csv('csv_from_scrape/davis_2017_df.csv')
davis_2017.columns.values[1] = 'DATE'
davis_2017.columns.values[2] = '2017 Batting Averages'
davis_2017.drop('Unnamed: 0', axis = 1)

     DATE  2017 Batting Averages
0   08-05                  0.250
1   08-08                  0.143
2   08-10                  0.091
3   08-12                  0.154
4   08-15                  0.188
5   08-17                  0.158
6   08-20                  0.136
7   08-22                  0.167
8   08-24                  0.192
9   08-25                  0.200
10  08-26                  0.176
11  08-29                  0.211
12  08-30                  0.200
13  08-31                  0.233
14  09-02                  0.250
15  09-02                  0.235
16  09-09                  0.235
17  09-10                  0.250
18  09-13                  0.241
19  09-22                  0.241
20  09-25                  0.241
21  09-26                  0.232
22  09-27                  0.228
23  09-28                  0.224
24  10-01                  0.226

In [6]:
frames = [dates, davis_2017]
drops = ['Unnamed: 0']

In [4]:
df_merged = reduce(lambda left,right: pd.merge(left,right,on=['DATE'], how='outer'), frames)

In [7]:
davis_batting = df_merged.drop(drops, axis=1)

In [8]:
davis_batting.to_csv('data_aggregated/davis_batting.csv', index=False)